import { describe, it, expect } from "vitest";
import { writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import {
  BASE_CONTRACTS,
  TEAM_IDS,
  rosterOf,
  allocateRotation,
  teamProjection,
  teamStrengthOf,
} from "@/lib/league";
import { DATA_AS_OF } from "@apron/data";

// ---------------------------------------------------------------------------
// REBASELINE the exported team-strength snapshot.
//
// team-strength-2026.json caches two MODEL-DERIVED numbers per team — `av` (the
// minutes-weighted Apron Value of the allocated rotation) and `projNrtg` (the
// model-native baseline net rating) — alongside two HISTORICAL ones, `nrtg` and
// `w`, which are the team's actual 2025-26 results and must never be recomputed.
//
// Rosters move every time the feeds refresh, so the two derived numbers go stale
// and impact.test.ts's "snapshot mirrors the model-native baseline" check fails.
// Regenerate with:
//
//   REBASELINE_TEAM_STRENGTH=1 npx vitest run lib/rebaselineTeamStrength.test.ts
//
// Without the env var this file only REPORTS the drift, so a normal test run
// never rewrites committed data as a side effect.
// ---------------------------------------------------------------------------

const FILE = join(__dirname, "..", "..", "..", "packages", "data", "src", "team-strength-2026.json");

/** Team Apron Value: the rotation's minutes-weighted average player Apron Value. */
function teamAv(team: string): number {
  const rot = allocateRotation(rosterOf(BASE_CONTRACTS, team));
  let min = 0;
  let weighted = 0;
  for (const slots of Object.values(rot.byPos)) {
    for (const s of slots) {
      min += s.minutes;
      weighted += s.minutes * s.av;
    }
  }
  return min > 0 ? Math.round((weighted / min) * 10) / 10 : 0;
}

describe("team-strength snapshot", () => {
  it("reports drift, and rewrites it when REBASELINE_TEAM_STRENGTH is set", () => {
    const raw = JSON.parse(readFileSync(FILE, "utf8")) as {
      source: string;
      asOf: string;
      calibration: unknown;
      byTeam: Record<string, { av: number; projNrtg: number; nrtg: number; w: number }>;
    };

    const rows = TEAM_IDS.map((t) => {
      const prev = raw.byTeam[t]!;
      return {
        t,
        prevAv: prev.av,
        prevNrtg: prev.projNrtg,
        av: teamAv(t),
        projNrtg: teamProjection(t, BASE_CONTRACTS)!.baseNrtg,
      };
    });

    const moved = rows.filter((r) => r.av !== r.prevAv || r.projNrtg !== r.prevNrtg);
    console.log(`\n  ${moved.length}/30 teams drifted since ${raw.asOf}`);
    console.log("  team   av (was)        projNrtg (was)");
    for (const r of [...moved].sort((a, b) => b.projNrtg - a.projNrtg))
      console.log(
        `  ${r.t.padEnd(4)} ${r.av.toFixed(1).padStart(6)} (${r.prevAv.toFixed(1)})   ` +
          `${r.projNrtg.toFixed(1).padStart(6)} (${r.prevNrtg.toFixed(1)})`,
      );

    if (!process.env.REBASELINE_TEAM_STRENGTH) {
      // The `av` formula is validated by the teams that did NOT move: if the
      // recomputation reproduces their committed values exactly, it is the same
      // function that produced the file.
      const unchanged = rows.filter((r) => r.av === r.prevAv);
      console.log(`\n  ${unchanged.length}/30 teams reproduce their committed av exactly (formula check)`);
      return;
    }

    const byTeam: Record<string, { av: number; projNrtg: number; nrtg: number; w: number }> = {};
    for (const r of rows) {
      const prev = raw.byTeam[r.t]!;
      // nrtg / w are 2025-26 FACTS — carried through untouched.
      byTeam[r.t] = { av: r.av, projNrtg: r.projNrtg, nrtg: prev.nrtg, w: prev.w };
    }
    const out = {
      ...raw,
      // The original file came from an external "apron-impact-model-hardened"
      // build that does not live in this repo, so its `av` column can't be
      // reproduced here. From this rebaseline forward `av` has an in-repo
      // definition (below) and is regenerated by this script — stated plainly
      // rather than left looking like continuous output of the old build.
      source:
        "team_strength_2026 — projNrtg from the in-repo model baseline " +
        "(leagueStandings over BASE_CONTRACTS); av = the allocateRotation " +
        "minutes-weighted mean of player Apron Value; nrtg/w are 2025-26 " +
        `actuals carried through untouched. Rebaselined ${DATA_AS_OF}.`,
      asOf: DATA_AS_OF,
      byTeam,
    };
    writeFileSync(FILE, JSON.stringify(out, null, 2) + "\n");
    console.log(`\n  REWROTE ${FILE} @ ${DATA_AS_OF}`);
    expect(moved.length).toBeGreaterThanOrEqual(0);
  });

  it("every team still carries its 2025-26 historical context", () => {
    for (const t of TEAM_IDS) {
      const s = teamStrengthOf(t)!;
      expect(s.w).toBeGreaterThan(0);
      expect(Number.isFinite(s.nrtg)).toBe(true);
    }
  });
});
